"""doctor_reviews tablosu

Revision ID: 72dffb9e5194
Revises: 7219b20bb9b5
Create Date: 2026-08-03 11:29:46.750838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72dffb9e5194'
down_revision: Union[str, Sequence[str], None] = '7219b20bb9b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('onaylanan_triage_code', sa.String(length=20), nullable=False),
    sa.Column('onaylanan_tetkikler', sa.JSON(), nullable=False),
    sa.Column('doktor_notu', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_reviews_visit_id'), 'doctor_reviews', ['visit_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctor_reviews_visit_id'), table_name='doctor_reviews')
    op.drop_table('doctor_reviews')
    # ### end Alembic commands ###
